### ISSUE TITLE
Problem with EspScopeA0 Delta

### ISSUE THREAD

**Issue by williamesp2015** [krzychb/EspScopeA0#1]
@krzychb 
......
Connected, IP address: 192.168.1.159
WebSockets started
HTTP server started
Open http://192.168.1.159/ to see the scope
//////////////////////////////// webpage shows chart, message box, Host: ws://192.168.1.159:81 Connect ... but immediately after click on connect says disconnected in red color. I couldn't past screenshot
/////////////////////
PS C:~PlatformIo\EspScopeA0> platformio platforms show espressif
espressif   - Espressif Systems is a privately held fabless semiconductor company. They provide wireless communications and Wi-Fi chips wh
## ich are widely used in mobile devices and the Internet of Things applications. [ https://espressif.com/ ]

Package: toolchain-xtensa
Alias: toolchain
Version: 2
## Installed: 2016-06-30 18:36:18

Package: tool-esptool
Alias: uploader
Version: 7
## Installed: 2016-06-30 18:49:24

Package: tool-mkspiffs
Alias: uploader
Version: 1
## Installed: 2016-06-30 18:51:01

Package: framework-arduinoespressif
Alias: framework
Version: 13
## Installed: 2016-06-30 18:49:50

Package: ldscripts
Version: 23
Installed: 2016-06-30 18:49:50
PS C:~PlatformIo\EspScopeA0>
///////////////////////
IE version 11.0.32
////////////////////
Windows 10
Thank you

**Comment by krzychb** [comment]
Hi @williamesp2015,

Congratulations on entering first issue on this repository :smile:

You have version 13 of framework-arduinoespressif which is the same that I have.
The only difference in s/w I see now is Windows version - you have Windows 10 and I have Windows 7.

Basing on the logs and description web sockets are unable to connect at all from your PC to ESP.
If they do, you would see a message on ESP like:

```
Open http://192.168.1.114/ to see the scope
[0] Connected from 192.168.1.101
[0] get Text: Hallo from Browser :-) Tue Jul 12 2016 19:12:26 GMT+0200 (Central European Daylight Time)
[0] get Text: ping
```

I guess this may be some security / blocking by a firewall or maybe some compatibility issue.

Unfortunately I do not have Windows 10 to check.
I will try to upgrade my PC to Windows 10 to replicate this issue.

Krzysztof

**Comment by krzychb** [comment]
@williamesp2015,

I have installed Windows 10.
EspScopeA0-Delta works out of box with Microsoft Edge web browser.

![web-browser-edge-scope-delta](https://cloud.githubusercontent.com/assets/12953787/16814400/f8821900-4935-11e6-8dd0-fb03efad583c.png)

I was thinking about enabling debugging to have some more clues why it does not work for you. Before doing so I propose couple of simple tests:
1. Verify if your router or firewall is not filtering out websocket's traffic on port 81. 
   You should be able to check it on http://portquiz.net/ by entering http://portquiz.net:81
   
   If port 81 is not filtered out, then you should see a message like:
   
   ![image](https://cloud.githubusercontent.com/assets/12953787/16814825/c9177992-4937-11e6-851c-afbc50806194.png)
2. Check if websockets are working at all with your web browser. You can do it e.g. on https://www.websocket.org/echo.html
   
   For me result is as follows:
   ![image](https://cloud.githubusercontent.com/assets/12953787/16814955/5c80e272-4938-11e6-92cf-e149c72170ae.png)
3. Verify independently if websockets out of web browser do communicate with EspScopeA0-Delta by following "Creating your own test" on the above web page.
   
   To do so replace `var wsUri = "ws://echo.websocket.org/";` with `var wsUri = "ws://192.168.1.114:81";` (substitute `192.168.1.114` with IP of your ESP). 
   
   Successful test looks as follows:
   
   ![image](https://cloud.githubusercontent.com/assets/12953787/16815364/d5eee734-4939-11e6-94fb-293e652f7c6e.png)

I wonder what will be the results for you.

Good luck :smile:

Krzysztof

**Comment by williamesp2015** [comment]
I really appreciate your help. All the tests results were OK and also I was changing host name in the websocketserver.h and returned to arduino but no success.
![image](https://cloud.githubusercontent.com/assets/12815126/16828191/cbc15f94-49a2-11e6-8ced-463cc961b73b.png)

**Comment by williamesp2015** [comment]
GOOD NEWS. I deleted the project and imported to PlatformIO a fresh project, changed SSID and password, It is working very nice. Thank you very much

**Comment by krzychb** [comment]
This is GREAT NEWS!
I am happy it works for you.
Thank you for update :smile:

**Comment by williamesp2015** [comment]
Hi Krzysztof, I think for faster communication when using external ADC, binary data would be the ultimate option. Do you have any suggestion for modify to binary using webSocket.sendBIN?

**Comment by krzychb** [comment]
Hi @williamesp2015,

Binary data transfer is on my "To Do" list planned for [Golf](https://github.com/krzychb/EspScopeA0/tree/master/Golf#golf-construction) version.
I would start with [MINKO GECHEV'S BLOG](http://blog.mgechev.com/2015/02/06/parsing-binary-protocol-data-javascript-typedarrays-blobs/).

Krzysztof
